"""phase 2 product state

Revision ID: f7e1ae8d09ba
Revises: 
Create Date: 2026-10-06 07:34:09.758551
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'f7e1ae8d09ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('identity_provider', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('owner_id'),
    sa.UniqueConstraint('identity_provider', 'subject', name='uq_owners_provider_subject')
    )
    op.create_table('audit_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('result_code', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('CASE_CREATED', 'CASE_UPDATED', 'CASE_DELETED', 'DOCUMENT_UPLOADED', 'DOCUMENT_REJECTED', 'DOCUMENT_DELETED', 'JOB_CREATED', 'JOB_COMPLETED', 'JOB_FAILED', 'JOB_CANCELLED')", name='ck_audit_events_type'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_audit_case_created', 'audit_events', ['case_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_owner_created', 'audit_events', ['owner_id', 'occurred_at', 'event_id'], unique=False)
    op.create_table('cases',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('claim_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'CREATED'"), nullable=False),
    sa.Column('deletion_status', sa.String(length=24), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('latest_analysis_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("deletion_status IN ('ACTIVE', 'DELETE_PENDING', 'DELETED')", name='ck_cases_deletion_status'),
    sa.CheckConstraint("status IN ('CREATED', 'AWAITING_DOCUMENTS', 'PROCESSING', 'NEEDS_REVIEW', 'ANALYZED', 'EVIDENCE_GAP', 'FAILED', 'DELETED')", name='ck_cases_status'),
    sa.CheckConstraint('version >= 1', name='ck_cases_version_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('case_id'),
    sa.UniqueConstraint('case_id', 'owner_id', name='uq_cases_case_owner')
    )
    op.create_index('ix_cases_owner_created', 'cases', ['owner_id', 'created_at', 'case_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('analysis_run_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('code_version', sa.String(length=80), nullable=True),
    sa.Column('rulepack_version', sa.String(length=80), nullable=True),
    sa.Column('corpus_snapshot_id', sa.String(length=128), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED')", name='ck_analysis_runs_status'),
    sa.CheckConstraint('run_number >= 1', name='ck_analysis_runs_number_positive'),
    sa.ForeignKeyConstraint(['case_id', 'owner_id'], ['cases.case_id', 'cases.owner_id'], name='fk_analysis_runs_case_owner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_run_id'),
    sa.UniqueConstraint('owner_id', 'case_id', 'analysis_run_id', name='uq_runs_owner_case_run'),
    sa.UniqueConstraint('owner_id', 'case_id', 'run_number', name='uq_analysis_runs_number')
    )
    op.create_index('ix_runs_owner_case_created', 'analysis_runs', ['owner_id', 'case_id', 'created_at'], unique=False)
    op.create_table('case_documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=24), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('policy_wording', 'policy_schedule', 'bill', 'settlement')", name='ck_case_documents_role'),
    sa.CheckConstraint("state IN ('RECEIVED', 'VALIDATING', 'QUEUED', 'PROCESSING', 'NEEDS_REVIEW', 'READY', 'PARTIAL', 'FAILED', 'DELETED')", name='ck_case_documents_state'),
    sa.CheckConstraint("byte_size > 0 OR state = 'DELETED'", name='ck_case_documents_byte_size_positive'),
    sa.CheckConstraint('length(sha256) = 64', name='ck_case_documents_sha256_length'),
    sa.CheckConstraint("page_count > 0 OR state = 'DELETED'", name='ck_case_documents_page_count_positive'),
    sa.ForeignKeyConstraint(['case_id', 'owner_id'], ['cases.case_id', 'cases.owner_id'], name='fk_case_documents_case_owner', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('owner_id', 'case_id', 'idempotency_key', name='uq_docs_idempotency')
    )
    op.create_index('ix_documents_owner_case_hash', 'case_documents', ['owner_id', 'case_id', 'sha256'], unique=False)
    op.create_index('ix_documents_owner_case_uploaded', 'case_documents', ['owner_id', 'case_id', 'uploaded_at', 'document_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('analysis_run_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'RETRYABLE_FAILURE', 'FAILED', 'CANCELLED')", name='ck_jobs_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_jobs_attempts_nonnegative'),
    sa.CheckConstraint('max_attempts >= 1', name='ck_jobs_max_attempts_positive'),
    sa.ForeignKeyConstraint(['case_id', 'owner_id'], ['cases.case_id', 'cases.owner_id'], name='fk_jobs_case_owner', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['case_documents.document_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('owner_id', 'case_id', 'idempotency_key', name='uq_jobs_idempotency'),
    sa.UniqueConstraint('owner_id', 'case_id', 'job_id', name='uq_jobs_owner_case_job')
    )
    op.create_index('ix_jobs_owner_case_created', 'processing_jobs', ['owner_id', 'case_id', 'created_at'], unique=False)
    op.create_index('ix_jobs_queue', 'processing_jobs', ['status', 'available_at', 'created_at'], unique=False)
    op.execute("""
        CREATE FUNCTION claimcheck_reject_audit_event_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events is append-only';
        END;
        $$;
    """)
    op.execute("""
        CREATE TRIGGER trg_audit_events_append_only
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION claimcheck_reject_audit_event_mutation();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_audit_events_append_only ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS claimcheck_reject_audit_event_mutation()")
    op.drop_index('ix_jobs_queue', table_name='processing_jobs')
    op.drop_index('ix_jobs_owner_case_created', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_documents_owner_case_uploaded', table_name='case_documents')
    op.drop_index('ix_documents_owner_case_hash', table_name='case_documents')
    op.drop_table('case_documents')
    op.drop_index('ix_runs_owner_case_created', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index('ix_cases_owner_created', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_audit_owner_created', table_name='audit_events')
    op.drop_index('ix_audit_case_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('owners')
    # ### end Alembic commands ###
