"""Private local filesystem implementation of the repository's existing Storage port."""
from __future__ import annotations

import hashlib
import os
import stat
import tempfile
from pathlib import Path, PurePosixPath

from claimcheck.ingest.model import StorageMetadata


class InvalidStorageKey(ValueError):
    """Raised when an opaque key could escape or alias the private storage root."""


class PrivateLocalFileStorage:
    """Atomic, permission-restricted local blob storage outside the web root.

    Callers use opaque keys only. No method accepts an original filename, and paths are never
    returned. Upload keys are generated by the application as a case UUID plus a random token.
    """

    def __init__(self, root: str | os.PathLike[str]) -> None:
        requested_root = Path(root).expanduser()
        if requested_root.exists() and requested_root.is_symlink():
            raise ValueError("Private storage root cannot be a symbolic link.")
        requested_root.mkdir(mode=0o700, parents=True, exist_ok=True)
        self.root = requested_root.resolve(strict=True)
        if not self.root.is_dir():
            raise ValueError("Private storage root must be a directory.")
        try:
            self.root.chmod(0o700)
        except OSError:
            # Readiness will fail if the directory is not writable; do not expose OS details.
            pass

    def _path(self, key: str) -> Path:
        if (not isinstance(key, str) or not key or key.startswith("/") or "\\" in key
                or "\x00" in key):
            raise InvalidStorageKey("Invalid storage key.")
        parts = key.split("/")
        if any(part in ("", ".", "..") for part in parts):
            raise InvalidStorageKey("Invalid storage key.")
        parsed = PurePosixPath(key)
        if parsed.is_absolute() or parsed.parts != tuple(parts):
            raise InvalidStorageKey("Invalid storage key.")

        target = self.root.joinpath(*parts)
        current = self.root
        for part in parts[:-1]:
            current = current / part
            if current.is_symlink():
                raise InvalidStorageKey("Invalid storage key.")
            if current.exists() and not current.is_dir():
                raise InvalidStorageKey("Invalid storage key.")
        if target.is_symlink():
            raise InvalidStorageKey("Invalid storage key.")
        try:
            resolved = target.resolve(strict=False)
            resolved.relative_to(self.root)
        except (OSError, ValueError) as exc:
            raise InvalidStorageKey("Invalid storage key.") from exc
        return target

    def put(self, key: str, data: bytes) -> str:
        if not isinstance(data, bytes):
            raise TypeError("Storage accepts bytes only.")
        target = self._path(key)
        target.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
        # Re-check after creating parents, so a substituted symlink is not traversed.
        target = self._path(key)
        fd, staging_name = tempfile.mkstemp(prefix=".staging-", dir=target.parent)
        try:
            os.fchmod(fd, 0o600)
            with os.fdopen(fd, "wb") as handle:
                handle.write(data)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(staging_name, target)
            os.chmod(target, 0o600, follow_symlinks=False)
        except Exception:
            try:
                os.close(fd)
            except OSError:
                pass
            try:
                os.unlink(staging_name)
            except FileNotFoundError:
                pass
            raise
        return key

    def get(self, key: str) -> bytes:
        target = self._path(key)
        flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
        descriptor = os.open(target, flags)
        try:
            info = os.fstat(descriptor)
            if not stat.S_ISREG(info.st_mode):
                raise FileNotFoundError
            with os.fdopen(descriptor, "rb", closefd=False) as handle:
                return handle.read()
        finally:
            os.close(descriptor)

    def exists(self, key: str) -> bool:
        target = self._path(key)
        return target.is_file() and not target.is_symlink()

    def delete(self, key: str) -> None:
        target = self._path(key)
        target.unlink(missing_ok=True)

    def metadata(self, key: str) -> StorageMetadata:
        data = self.get(key)
        return StorageMetadata(size_bytes=len(data), sha256=hashlib.sha256(data).hexdigest())

    def check_ready(self) -> bool:
        """Check that private storage is writable without returning its path."""
        self.root.mkdir(mode=0o700, parents=True, exist_ok=True)
        descriptor, probe_name = tempfile.mkstemp(prefix=".health-check-", dir=self.root)
        try:
            os.fchmod(descriptor, 0o600)
            os.close(descriptor)
            descriptor = -1
        finally:
            if descriptor >= 0:
                os.close(descriptor)
            try:
                os.unlink(probe_name)
            except FileNotFoundError:
                pass
        return True

